name = "pagenest"
compatibility_date = "2026-03-09"
pages_build_output_dir = "dist"

[vars]
APP_ENV = "development"

[[d1_databases]]
binding = "DB"
database_name = "pagenest"
database_id = "ba7df79c-b2ec-4c9b-9db4-1897f43ea4f2"
migrations_dir = "db/migrations"

[[r2_buckets]]
binding = "LIBRARY_BUCKET"
bucket_name = "pagenest-library"
preview_bucket_name = "pagenest-library-preview"

